name: Code Review
permissions:
  contents: read
  pull-requests: write
on:
  pull_request_review_comment:
    types: [created, deleted]

 

jobs:
  code-review:
    runs-on: ubuntu-latest
    steps:
    - name: OpenAI ChatGPT CodeReview 2023
      uses: manjunathsb100/chatgpt-code-review-action@v0.7
      with:
        PROGRAMMING_LANGUAGE: 'JavaScript'
        OPENAI_TOKEN: ${{ secrets.OPENAI_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        FULL_REVIEW_COMMENT: 'chatgpt'
        REVIEW_COMMENT_PREFIX: 'chatgpt:'
